/*
* This file was generated by the SGE Code Gen.
* Please dont edit this file manually. 
*/

#include "Core.h"
#include "ObjectBase.h"

using namespace sge;

Class* constructMyClassClass()
{
    Class* clazz = new Class();
    clazz->uid = { 1125743140, 95212};
    clazz->name = "MyClass";
    clazz->size = sizeof(MyClass);
return clazz;
}

Class* MyClass::type()
{
    static Class* clazz = constructMyClassClass();
    return clazz;
}
