/*
* This file was generated by the SGE Code Gen.
* Please dont edit this file manually. 
*/

#if defined(MyClass_GENERATED)
    #undef MyClass_GENERATED
#endif
#define MyClass_GENERATED()\
static sge::Class* type();

